"""Update student model with registration fields

Revision ID: a2b3380b924e
Revises: 
Create Date: 2025-09-18 19:32:24.684405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2b3380b924e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_otps_email_phone'), table_name='otps')
    op.drop_index(op.f('idx_otps_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_purpose'), table_name='otps')
    op.drop_index(op.f('idx_otps_user'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('idx_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_resource'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_sponsorships_active'), table_name='sponsorships')
    op.drop_index(op.f('idx_sponsorships_institution'), table_name='sponsorships')
    op.drop_index(op.f('idx_sponsorships_status'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('idx_payments_active'), table_name='payments')
    op.drop_index(op.f('idx_payments_institution'), table_name='payments')
    op.drop_index(op.f('idx_payments_registration'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.drop_index(op.f('idx_payments_transaction'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('idx_notifications_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('idx_documents_active'), table_name='documents')
    op.drop_index(op.f('idx_documents_owner'), table_name='documents')
    op.drop_index(op.f('idx_documents_uploaded_by'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('idx_registrations_active'), table_name='registrations')
    op.drop_index(op.f('idx_registrations_category'), table_name='registrations')
    op.drop_index(op.f('idx_registrations_payment'), table_name='registrations')
    op.drop_index(op.f('idx_registrations_status'), table_name='registrations')
    op.drop_index(op.f('idx_registrations_student'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('idx_institutions_active'), table_name='institutions')
    op.drop_index(op.f('idx_institutions_email'), table_name='institutions')
    op.drop_index(op.f('idx_institutions_name'), table_name='institutions')
    op.drop_index(op.f('idx_institutions_registration'), table_name='institutions')
    op.drop_index(op.f('user_id'), table_name='institutions')
    op.create_index(op.f('ix_institutions_email'), 'institutions', ['email'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_registration_number'), 'institutions', ['registration_number'], unique=False)
    op.create_index(op.f('ix_institutions_user_id'), 'institutions', ['user_id'], unique=True)
    op.drop_constraint(op.f('institutions_ibfk_1'), 'institutions', type_='foreignkey')
    op.create_foreign_key(None, 'institutions', 'users', ['user_id'], ['id'])
    op.alter_column('sport_categories', 'gender_allowed',
               existing_type=mysql.ENUM('male', 'female', 'mixed', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_sport_categories_active'), table_name='sport_categories')
    op.drop_index(op.f('idx_sport_categories_sport'), table_name='sport_categories')
    op.create_index(op.f('ix_sport_categories_id'), 'sport_categories', ['id'], unique=False)
    op.drop_constraint(op.f('sport_categories_ibfk_1'), 'sport_categories', type_='foreignkey')
    op.create_foreign_key(None, 'sport_categories', 'sports', ['sport_id'], ['id'])
    op.drop_index(op.f('idx_sports_active'), table_name='sports')
    op.drop_index(op.f('idx_sports_name'), table_name='sports')
    op.drop_index(op.f('idx_sports_slug'), table_name='sports')
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('institution_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('parent_guardian_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('parent_email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('emergency_contact_relation', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('emergency_contact_email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('medical_question_1', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('medical_question_2', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('has_allergies', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('allergies_details', sa.String(length=1000), nullable=True))
    op.add_column('students', sa.Column('participation_type', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('selected_sports', sa.JSON(), nullable=True))
    op.add_column('students', sa.Column('student_id_image', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('age_proof_image', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_index(op.f('idx_students_active'), table_name='students')
    op.drop_index(op.f('idx_students_institution'), table_name='students')
    op.drop_index(op.f('idx_students_student_id'), table_name='students')
    op.drop_index(op.f('user_id'), table_name='students')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.drop_constraint(op.f('students_ibfk_1'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_ibfk_2'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'students', 'institutions', ['institution_id'], ['id'])
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'institute', 'student', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('idx_users_active'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'institute', 'student', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_ibfk_2'), 'students', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('students_ibfk_1'), 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_index(op.f('user_id'), 'students', ['user_id'], unique=True)
    op.create_index(op.f('idx_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('idx_students_institution'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('idx_students_active'), 'students', ['is_active'], unique=False)
    op.drop_column('students', 'is_verified')
    op.drop_column('students', 'age_proof_image')
    op.drop_column('students', 'student_id_image')
    op.drop_column('students', 'selected_sports')
    op.drop_column('students', 'participation_type')
    op.drop_column('students', 'allergies_details')
    op.drop_column('students', 'has_allergies')
    op.drop_column('students', 'medical_question_2')
    op.drop_column('students', 'medical_question_1')
    op.drop_column('students', 'emergency_contact_email')
    op.drop_column('students', 'emergency_contact_phone')
    op.drop_column('students', 'emergency_contact_relation')
    op.drop_column('students', 'emergency_contact_name')
    op.drop_column('students', 'parent_email')
    op.drop_column('students', 'parent_phone')
    op.drop_column('students', 'parent_guardian_name')
    op.drop_column('students', 'institution_name')
    op.drop_column('students', 'email')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.create_index(op.f('idx_sports_slug'), 'sports', ['slug'], unique=False)
    op.create_index(op.f('idx_sports_name'), 'sports', ['name'], unique=False)
    op.create_index(op.f('idx_sports_active'), 'sports', ['is_active'], unique=False)
    op.drop_constraint(None, 'sport_categories', type_='foreignkey')
    op.create_foreign_key(op.f('sport_categories_ibfk_1'), 'sport_categories', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sport_categories_id'), table_name='sport_categories')
    op.create_index(op.f('idx_sport_categories_sport'), 'sport_categories', ['sport_id'], unique=False)
    op.create_index(op.f('idx_sport_categories_active'), 'sport_categories', ['is_active'], unique=False)
    op.alter_column('sport_categories', 'gender_allowed',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('male', 'female', 'mixed', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_constraint(None, 'institutions', type_='foreignkey')
    op.create_foreign_key(op.f('institutions_ibfk_1'), 'institutions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_institutions_user_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_registration_number'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_email'), table_name='institutions')
    op.create_index(op.f('user_id'), 'institutions', ['user_id'], unique=True)
    op.create_index(op.f('idx_institutions_registration'), 'institutions', ['registration_number'], unique=False)
    op.create_index(op.f('idx_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('idx_institutions_email'), 'institutions', ['email'], unique=False)
    op.create_index(op.f('idx_institutions_active'), 'institutions', ['is_active'], unique=False)
    op.create_table('registrations',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('student_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('sport_category_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'confirmed', 'rejected', 'cancelled'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payment_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('documents', mysql.JSON(), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sport_category_id'], ['sport_categories.id'], name='registrations_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='registrations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_registrations_student'), 'registrations', ['student_id'], unique=False)
    op.create_index(op.f('idx_registrations_status'), 'registrations', ['status'], unique=False)
    op.create_index(op.f('idx_registrations_payment'), 'registrations', ['payment_id'], unique=False)
    op.create_index(op.f('idx_registrations_category'), 'registrations', ['sport_category_id'], unique=False)
    op.create_index(op.f('idx_registrations_active'), 'registrations', ['is_active'], unique=False)
    op.create_table('documents',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('owner_type', mysql.ENUM('student', 'institution'), nullable=False),
    sa.Column('owner_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('size_bytes', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('storage_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False),
    sa.Column('uploaded_by', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('documents_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_documents_owner'), 'documents', ['owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('idx_documents_active'), 'documents', ['is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('body', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('idx_notifications_read'), 'notifications', ['is_read'], unique=False)
    op.create_table('payments',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('registration_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('institution_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'completed', 'failed', 'refunded'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('provider_payload', mysql.JSON(), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('payments_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('payments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_payments_transaction'), 'payments', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_registration'), 'payments', ['registration_id'], unique=False)
    op.create_index(op.f('idx_payments_institution'), 'payments', ['institution_id'], unique=False)
    op.create_index(op.f('idx_payments_active'), 'payments', ['is_active'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('institution_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('sponsor_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('terms', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('sponsorships_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_sponsorships_status'), 'sponsorships', ['status'], unique=False)
    op.create_index(op.f('idx_sponsorships_institution'), 'sponsorships', ['institution_id'], unique=False)
    op.create_index(op.f('idx_sponsorships_active'), 'sponsorships', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('actor_user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('resource_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('resource_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('metadata', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_audit_logs_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_actor'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('otps',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('email_or_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('purpose', mysql.ENUM('registration', 'login', 'password_reset'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otps_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_otps_user'), 'otps', ['user_id'], unique=False)
    op.create_index(op.f('idx_otps_purpose'), 'otps', ['purpose'], unique=False)
    op.create_index(op.f('idx_otps_expires'), 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email_phone'), 'otps', ['email_or_phone'], unique=False)
    # ### end Alembic commands ###
