<<<<<<< HEAD
// Institution data constants and utility functions

export const INSTITUTE_TYPES = [
  "School",
  "College",
  "University",
  "Sports Academy",
  "Sports Club",
  "Other"
];

// Institution data by type
export const INSTITUTION_DATA = {
  "School": [
    "Delhi Public School",
    "Kendriya Vidyalaya",
    "Army Public School",
    "DPS International",
    "The Doon School",
    "Mayo College",
    "St. Stephen's School",
    "Modern School",
    "Vasant Valley School",
    "Springdales School",
    "Apeejay School",
    "Ryan International School",
    "DAV Public School",
    "Bharatiya Vidya Bhavan",
    "Sanskriti School",
    "The Shri Ram School",
    "Amity International School",
    "GD Goenka School",
    "Heritage School",
    "Lotus Valley School"
  ],
  "College": [
    "St. Stephen's College",
    "Hindu College",
    "Lady Shri Ram College",
    "Miranda House",
    "Hansraj College",
    "Ramjas College",
    "Kirori Mal College",
    "Gargi College",
    "Jesus and Mary College",
    "Kamala Nehru College",
    "Sri Venkateswara College",
    "Acharya Narendra Dev College",
    "Deen Dayal Upadhyaya College",
    "Keshav Mahavidyalaya",
    "Maitreyi College",
    "Motilal Nehru College",
    "Rajdhani College",
    "Shyam Lal College",
    "Swami Shraddhanand College",
    "Vivekananda College"
  ],
  "University": [
    "University of Delhi",
    "Jawaharlal Nehru University",
    "Jamia Millia Islamia",
    "Ambedkar University Delhi",
    "Guru Gobind Singh Indraprastha University",
    "Netaji Subhas University of Technology",
    "Delhi Technological University",
    "Indraprastha Institute of Information Technology",
    "National Institute of Technology Delhi",
    "Indian Institute of Technology Delhi",
    "All India Institute of Medical Sciences",
    "Jamia Hamdard University",
    "Shiv Nadar University",
    "Ashoka University",
    "OP Jindal Global University",
    "Amity University",
    "Galgotias University",
    "Bennett University",
    "Manav Rachna University",
    "SRM University"
  ],
  "Sports Academy": [
    "Sports Authority of India",
    "National Institute of Sports",
    "Patiala Sports Academy",
    "Bangalore Sports Academy",
    "Mumbai Sports Academy",
    "Chennai Sports Academy",
    "Kolkata Sports Academy",
    "Delhi Sports Academy",
    "Pune Sports Academy",
    "Hyderabad Sports Academy",
    "Ahmedabad Sports Academy",
    "Chandigarh Sports Academy",
    "Bhopal Sports Academy",
    "Jaipur Sports Academy",
    "Lucknow Sports Academy",
    "Bhubaneswar Sports Academy",
    "Guwahati Sports Academy",
    "Kochi Sports Academy",
    "Indore Sports Academy",
    "Vadodara Sports Academy"
  ],
  "Sports Club": [
    "Delhi Sports Club",
    "Mumbai Sports Club",
    "Bangalore Sports Club",
    "Chennai Sports Club",
    "Kolkata Sports Club",
    "Pune Sports Club",
    "Hyderabad Sports Club",
    "Ahmedabad Sports Club",
    "Chandigarh Sports Club",
    "Bhopal Sports Club",
    "Jaipur Sports Club",
    "Lucknow Sports Club",
    "Bhubaneswar Sports Club",
    "Guwahati Sports Club",
    "Kochi Sports Club",
    "Indore Sports Club",
    "Vadodara Sports Club",
    "Surat Sports Club",
    "Nashik Sports Club",
    "Vijayawada Sports Club"
  ],
  "Other": []
};

// Utility function to get institution options based on type
export function getInstituteOptions(instituteType: string): string[] {
  if (instituteType === "Other") {
    return []; // Return empty array for "Other" type
  }
  
  return INSTITUTION_DATA[instituteType as keyof typeof INSTITUTION_DATA] || [];
}


=======
// Institution data constants shared between admin panel and registration forms

export const KAISO_SCHOOLS = [
  "Aga Khan Academy",
  "Braeburn Garden Estate - BGE",
  "Braeburn Gitanga Road - BGR",
  "Braeside School, Thika",
  "Braeside School, Lavington",
  "Brookhouse School, Karen",
  "Brookhouse School, Runda",
  "Brookhurst International, Lavington",
  "Brookhurst International, Kiserian",
  "Crawford International School",
  "The Banda School",
  "French School",
  "German School",
  "Jawabu School",
  "Light International School",
  "Makini Cambridge School",
  "Nairobi Academy",
  "Nairobi Jaffery Academy",
  "Oshwal Academy U15 & U17",
  "Oshwal Academy U17 & U19",
  "Peponi School (overall)",
  "Peponi School (Girls Sport)",
  "Peponi School (Boys Sport)",
  "Rosslyn Academy (overall)",
  "Kenton College",
  "Rusinga School",
  "SABIS International School",
  "St Austin's Academy",
  "St. Christopher's School",
  "Swedish School",
  "Woodcreek School",
  "West Nairobi School - WNS",
  "ISK",
  "Durham International School - DIS",
];

export const GOVERNMENT_SCHOOLS = [
  "MBAGATHI ROAD PRIMARY",
  "NEMBU PRIMARY",
  "KAWANGWARE PRIMARY",
  "TOI PRIMARY",
  "RIRUTA HGM PRIMARY",
  "DAGORETTI MUSLIM PRIMARY",
  "KINYANJUI ROAD PRIMARY",
  "JOSEPH KANGETHE PRIMARY",
  "JAMHURI PRIMARY",
  "GATINA PRIMARY",
  "MUTUINI PRIMARY",
  "MUKARARA",
  "DAGORETTI GIRLS REHABILITATION",
  "WORLD HOPE ACADEMY",
  "KAGIRA PRIMARY",
  "KIRIGU PRIMARY",
  "RUTHIMITU PRIMARY",
  "WAITHAKA SPECIAL SCHOOL",
  "DR. MUTHIORA PRIMARY",
  "GITIBA PRIMARY",
  "RIRUTA SATELLITE PRIMARY",
  "KABIRIA PRIMARY SCHOOL",
  "SHADRACK KIMALEL PRIMARY SCHOOL",
  "NDURARUA PRIMARY",
  "UPPER HILL DAY NURSERY",
  "UMOJA PRIMARY",
  "RONALD NGALA PRIMARY",
  "USHIRIKA PRIMARY",
  "KARIOBANGI SOUTH PRIMARY",
  "TOM MBOYA PRIMARY",
  "GITUAMBA PRIMARY",
  "PETER KIBUKOSYA PRIMARY",
  "ATHI PRIMARY",
  "RUAI PRIMARY",
  "JEHOVAH JIREH PRIMARY",
  "NGUNDU PRIMARY",
  "UNITY PRIMARY",
  "UTAWALA ACADEMY",
  "KAYOLE I PRIMARY",
  "TUMAINI PRIMARY",
  "OUR LADY OF NAZARETH PRIMARY",
  "MAUA PRIMARY",
  "VISIONS PRIMARY (MIHANG'O)",
  "EMBAKASI GARRISON PRIMARY",
  "MWANGAZA PRIMARY",
  "EMBAKASI PRIMARY",
  "THAWABU PRIMARY",
  "BONDENI PRIMARY",
  "KOMAROCK PRIMARY",
  "KIFARU PRIMARY",
  "EDELVALE PRIMARY",
  "IMARA PRIMARY",
  "DOONHOLM PRIMARY",
  "BUSARA PRIMARY",
  "A.E.F. REUBEN PRIMARY",
  "KWA NJENGA PRIMARY",
  "DANDORA PRIMARY SCHOOL",
  "SIMBA DAY NURSERY",
  "MUGUMO DAY NURSERY",
  "MWANGAZA DAY NURSERY",
  "UNITY DAY NURSERY",
  "UMOJA I DAY NURSERY",
  "ST. DOMINIC'S PRIMARY SCHOOL",
  "KAYOLE NORTH PRIMARY",
  "KANGUNDO ROAD PRY",
  "JAMES GICHURU PRIMARY",
  "WANGU PRIMARY",
  "DRUMVALE PRIMARY",
  "NJIRU PRIMARY",
  "EASTLEIGH AIRPORT PRIMARY",
  "MUTHURWA PRIMARY",
  "UHURU ESTATE PRIMARY",
  "HESHIMA ROAD PRIMARY",
  "OUR LADY OF MERCY GIRLS - SHAURI MOYO",
  "BAHATI UHURU PRIMARY",
  "KIMATHI PRIMARY",
  "MORRISON PRIMARY",
  "DR. LIVINGSTONE PRIMARY",
  "NAIROBI RIVER PRIMARY",
  "NEW EASTLEIGH PRIMARY",
  "ZAWADI PRIMARY",
  "MOI AIR BASE PRIMARY",
  "MOI FORCES ACADEMY",
  "ST. TERESA'S BOYS PRIMARY SCHOOL",
  "BAHATI DAY NURSERY",
  "NEW PUMWANNI PRIMARY",
  "BURUBURU I PRIMARY",
  "ROYSAMBU PRIMARY",
  "KAHAWA PRIMARY",
  "KAMITI PRIMARY",
  "KAWAHA GARRISON SECONDARY",
  "GITHURAI PRIMARY",
  "GARDEN ESTATE PRIMARY",
  "KENYATTA UNIVERSITY PRIMARY",
  "MAHIGA PRIMARY",
  "KIWANJA PRIMARY",
  "MARURUI PRIMARY",
  "NJATHAINI PRIMARY",
  "NGUNYUMU PRIMARY",
  "MATHARE 4A PRIMARY",
  "THIKA ROAD PRIMARY",
  "G.S.U. PRIMARY",
  "DANIEL COMBONI PRIMARY",
  "MUTHAIGA PRIMARY",
  "MARURA PRIMARY",
  "M.M. CHANDARIA PRIMARY",
  "KASARANI PRIMARY",
  "KARIOBANGI NORTH GIRLS SECONDARY SCHOOL",
  "MUREMA PRIMARY",
  "MATHARE NORTH PRIMARY SCHOOL",
  "BABA DOGO PRIMARY SCHOOL",
  "DRIVE-IN PRIMARY SCHOOL",
  "TREESIDE SPECIAL SCHOOL",
  "KAREN 'C' PRIMARY",
  "NGONG FOREST PRIMARY",
  "ST. MARY'S KAREN PRIMARY",
  "AYANY PRIMARY",
  "LANGATA ROAD PRIMARY",
  "RAILA EDUCATION CENTRE",
  "NGEI PRIMARY",
  "KONGONI PRIMARY",
  "LANGATA WEST PRIMARY",
  "UHURU GARDENS PRIMARY",
  "MADARAKA PRIMARY SCHOOL",
  "OLYMPIC PRIMARY",
  "LANGATA BARRACKS PRIMARY",
  "KIBERA PRIMARY",
  "NAIROBI WEST DAY NUSERY",
  "RABAI ROAD PRIMARY",
  "BARAKA PRIMARY",
  "HARAMBEE PRIMARY",
  "OFAFA JERICHO PRIMARY",
  "ST. MICHAEL'S PRIMARY",
  "ST. ANNE'S PRIMARY",
  "DR. KRAPF PRIMARY",
  "JOGOO ROAD PRIMARY",
  "ST. PAUL'S PRIMARY",
  "MARTIN LUTHER PRIMARY",
  "MARIAKANI PRIMARY",
  "STAR OF HOPE LUNGA LUNGA",
  "JOSEPH APUDO PRIMARY",
  "MAKONGENI PRIMARY",
  "OUR LADY OF MERCY SOUTH 'B'",
  "PLAINSVIEW PRIMARY",
  "ST. ELIZABETH LUNGA LUNGA",
  "ST. BAKHITA PRIMARY",
  "MUKURU PRIMARY",
  "NAIROBI SOUTH PRIMARY",
  "NILE ROAD SPECIAL SCHOOL",
  "ST. JOHN'S PRIMARY",
  "BIDII PRIMARY",
  "KALOLENI PRIMARY",
  "ST. PATRICK'S PRIMARY SCHOOL",
  "TANA DAY NURSERY",
  "NJORO CLOSE DAY NURSERY SCHOOL",
  "OFAFA DAY NURSERY",
  "KALOLENI DAY NURSERY",
  "MBOTELA DAY NURSERY",
  "ST. CATHERINE'S PRIMARY",
  "CANON APOLO PRIMARY",
  "RIVER BANK PRIMARY",
  "PUMWANI PRIMARY",
  "S.S.D. PRIMARY",
  "MURANG'A ROAD PRIMARY",
  "PARKLANDS PRIMARY",
  "DR. AGGREY PRIMARY",
  "MATHARI PRIMARY",
  "NDURURUNO PRIMARY",
  "AINSWOTH STREET PRIMARY",
  "ARYA PRIMARY",
  "KIBORO PRIMARY",
  "NG'ETHU WATER WORKS",
  "RACECOURSE PRIMARY",
  "VALLEY BRIDGE PRIMARY",
  "SALAMA PRIMARY",
  "MUSLIM PRIMARY",
  "ST. TERESA'S GIRLS PRIMARY",
  "ISLAMIA PRIMARY",
  "ST. BRIGIDS PRIMARY",
  "PANGANI PRIMARY",
  "HURUMA PRIMARY",
  "MOI AVENUE PRIMARY",
  "ST. PETER CLAVERS PRIMARY",
  "CITY PRIMARY",
  "PARKROAD PRIMARY",
  "C.G.H.U. PRIMARY",
  "JUJA ROAD PRIMARY",
  "PUMWANI PRIMARY SCHOOL",
  "CENTRAL DAY CURSERY",
  "PARKLANDS DAY NURSERY",
  "NGARA EAST DAY NURSERY",
  "STAREHE DAY NURSERY",
  "ZIWANI DAY NURSERY",
  "DAIMA PRIMARY",
  "MATHARE TECHNICAL SPECIAL",
  "KABETE VET LAB PRIMARY",
  "KIHUMBUINI PRIMARY",
  "NAIROBI PRIMARY",
  "MILIMANI PRIMARY",
  "LAVINGTON PRIMARY SCHOOL",
  "STATE HOUSE PRIMARY",
  "KILELESHWA PRIMARY",
  "NEW KIHUMBUINI PRIMARY",
  "KILIMANI PRIMARY",
  "AGA KHAN PRIMARY",
  "FARASI LANE PRIMARY",
  "VISA OSHWAL PRIMARY - NAIROBI",
  "BOHRA PRIMARY SCHOOL",
  "KABETE REHABILITATION SCHOOL",
  "HOSPITAL HILL PRIMARY",
  "HIGHRIDGE PRIMARY",
  "JACARANDA SPECIAL SCHOOL",
  "NORTH HIGHRIDGE PRIMARY",
  "MUGUGA GREEN PRIMARY",
  "WESTLANDS PRIMARY",
  "KARURA FOREST PRIMARY",
  "CHELETA PRIMARY",
  "LOWER KABETE PRIMARY",
  "KANGEMI PRIMARY",
  "ST. GEORGE'S PRIMARY",
  "LORESHO PRIMARY",
  "STATE HOUSE DAY NURSERY",
  "KILELESHWA DAY NURSERY",
  "LADY NORTHEY DAY NURSERY",
  "HIGHWAY SECONDARY SCHOOL",
  "PARKLANDS BAPTIST SCHOOL",
];

export const ACADEMICS = [
  "Talanta",
  "JB Academy",
  "Muqs",
  "Bumble Bee Sports",
  "Discovery Tennis",
  "TY SPORTS",
  "Terriffic Tennis",
  "TY SPORTS",
  "Next Gen Multi Sport Academu",
];

export const INSTITUTE_TYPES = [
  "Kaiso School",
  "Government School",
  "Academics",
  "Other",
] as const;

export const getInstituteOptions = (type: string): string[] => {
  switch (type) {
    case "Kaiso School":
      return KAISO_SCHOOLS;
    case "Government School":
      return GOVERNMENT_SCHOOLS;
    case "Academics":
      return ACADEMICS;
    default:
      return [];
  }
};

>>>>>>> 47379439 (improved the admin panel more to go)
